"""empty message

Revision ID: 3d0102485013
Revises: 552323647a4e
Create Date: 2022-03-16 18:10:14.896850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0102485013'
down_revision = '552323647a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_doctor', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('field_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'fields', ['field_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'field_id')
    op.drop_column('users', 'is_doctor')
    # ### end Alembic commands ###
