"""empty message

Revision ID: 60555178f54a
Revises: a4688c969931
Create Date: 2022-03-18 02:47:01.012394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60555178f54a'
down_revision = 'a4688c969931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'answered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'answered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
