"""empty message

Revision ID: efe1ccca7450
Revises: 60555178f54a
Create Date: 2022-03-20 20:39:31.162307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe1ccca7450'
down_revision = '60555178f54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
