"""empty message

Revision ID: 552323647a4e
Revises: 9c433e04b342
Create Date: 2022-03-14 19:07:42.491094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552323647a4e'
down_revision = '9c433e04b342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('field_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'fields', ['field_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'field_id')
    op.drop_column('posts', 'user_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post_id')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
